"""Training logic for MINOTAUR."""
import os
import torch
import numpy as np
import pandas as pd
import pytorch_lightning as pl
from typing import List, Tuple, Optional, Any
from torch.utils.data import DataLoader
from pytorch_lightning.loggers import TensorBoardLogger

# TODO: Update imports after removing old cem_mil package
from fedcbm.models import ConceptEmbeddingModel
from fedcbm.data import get_data_loaders
from fedcbm.training.callbacks import AttentionHook, SaveAttentionCallback
from fedcbm.training.utils import (
    get_concept_weights,
    get_cptprobs,
    get_yprobs,
    get_cembs,
    get_contexts,
    get_concept_attention_weights,
    build_predictions_dataframe,
)
from fedcbm.training.metrics import (
    compute_task_metrics_all,
    compute_concept_metrics,
)
from sklearn.model_selection import train_test_split


def split_train_val(
    train_cohort: pd.DataFrame,
    concepts: List[str],
    config
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split dataset into train and validation sets with optional concept stratification.
    
    Args:
        train_cohort: Full training dataset DataFrame
        concepts: List of concept column names
        config: Configuration object
        
    Returns:
        Tuple of (train_data, val_data) DataFrames
    """
    # Split data
    if not config.concepts.no_concepts:
        train_cohort['stratify_col'] = train_cohort[concepts[:2]].astype(str).agg('-'.join, axis=1)
        train_df, val_df = train_test_split(
            train_cohort,
            test_size=config.data.test_size,
            stratify=train_cohort['stratify_col'],
            random_state=config.data.stratify_random_state
        )
    else:
        # No concepts mode: simple train/val split without concept stratification
        train_df, val_df = train_test_split(
            train_cohort,
            test_size=config.data.test_size,
            random_state=config.data.stratify_random_state
        )
    
    train_ids, val_ids = list(train_df['ID']), list(val_df['ID'])
    train_cohort['test'] = train_cohort['ID'].apply(lambda x: 1 if x in train_ids else 0)
    
    train_data = train_cohort[train_cohort['test'] == 1]
    val_data = train_cohort[train_cohort['test'] == 0]
    
    return train_data, val_data


def train_model(train_dloader, val_dloader, config, experiment_name: Optional[str] = None, version: Optional[str] = None):
    """Train a CEM-MIL model.
    
    Args:
        train_dloader: Training data loader
        val_dloader: Validation data loader
        config: Configuration object
        experiment_name: Optional experiment name for TensorBoard. If None, uses config.output.name
        version: Optional version string for TensorBoard. If None, auto-generated by TensorBoardLogger
        
    Returns:
        Tuple of (model, trainer)
    """
    # Use provided experiment_name or fall back to config
    name = experiment_name if experiment_name is not None else config.output.name
    logger1 = TensorBoardLogger(config.output.save_path, name=name, version=version)
    
    attention_hook = None
    atten_callback = None
    if config.model.attn:
        attention_hook = AttentionHook()
        atten_callback = SaveAttentionCallback(attention_hook=attention_hook)
    
    # Initialize model
    cem_model = ConceptEmbeddingModel(
        n_concepts=config.concepts.n_concepts,
        concept_states=config.concepts.concept_states,
        n_tasks=config.model.n_tasks,
        h_dim=config.model.h_dim,
        pre_bn_mlp=config.model.pre,
        emb_size=config.model.emb_dim,
        embedding_activation=config.model.emb_activ,
        concept_loss_weight=config.model.c_weight,
        concept_class_weights=torch.tensor(config.concepts.cpt_cls_weights) 
            if config.concepts.cpt_cls_weights is not None else None,
        learning_rate=config.training.learning_rate,
        dropout=config.model.dropout,
        optimizer=config.training.optimizer,
        attention_hook=attention_hook,
        no_concepts=config.concepts.no_concepts,
        task_type=config.task_type
    )
    
    # Setup callbacks
    callbacks = []
    if atten_callback is not None:
        callbacks.append(atten_callback)
    
    # Initialize trainer
    trainer = pl.Trainer(
        accelerator=config.hardware.accelerator,
        devices=config.hardware.devices,
        max_epochs=config.training.max_epochs,
        check_val_every_n_epoch=config.training.check_val_every_n_epoch,
        callbacks=callbacks,
        enable_progress_bar=config.hardware.enable_progress_bar,
        logger=logger1
    )

    trainer.fit(cem_model, train_dloader, val_dloader)
    return cem_model, trainer


def predict(model, val_dloader, config):
    """Run prediction on validation data.
    
    Args:
        model: Trained model
        val_dloader: Validation data loader
        config: Configuration object
        
    Returns:
        List containing [c_probs, c_test, y_probs, y_test, c_embs, ctxts, concept_attention_weights, patient_ids]
    """
    x_test, y_test, c_test, patient_ids_list = [], [], [], []
    is_cox = config.task_type == 'cox'
    
    for (x, y, c, wsi_id) in val_dloader:
        x_test.append(x)
        patient_ids_list.extend(wsi_id if isinstance(wsi_id, (list, tuple)) else [wsi_id])
        if is_cox:
            event, survtime = y
            y_test.append((
                event.numpy() if isinstance(event, torch.Tensor) else event,
                survtime.numpy() if isinstance(survtime, torch.Tensor) else survtime
            ))
        else:
            y_test.append(y)
        c_test.append(c)
    
    x_test = np.concatenate(x_test, axis=0)
    
    if is_cox:
        # For Cox, y_test is a list of tuples, need to handle differently
        events_list = []
        survtimes_list = []
        for y_tuple in y_test:
            event, survtime = y_tuple
            if isinstance(event, torch.Tensor):
                events_list.append(event.cpu().numpy())
            else:
                events_list.append(np.array(event))
            if isinstance(survtime, torch.Tensor):
                survtimes_list.append(survtime.cpu().numpy())
            else:
                survtimes_list.append(np.array(survtime))
        
        events = np.concatenate(events_list, axis=0) if len(events_list[0].shape) > 0 else np.array(events_list)
        survtimes = np.concatenate(survtimes_list, axis=0) if len(survtimes_list[0].shape) > 0 else np.array(survtimes_list)
        y_test = (events, survtimes)
        
        # Debug: Print aggregated test data statistics
        print(f"\n[COX DEBUG] predict: Aggregated validation/test data")
        print(f"  - Total samples: {len(events)}")
        print(f"  - events shape: {events.shape}, dtype: {events.dtype}")
        print(f"  - events stats: min={events.min()}, max={events.max()}, "
              f"sum={events.sum()} (n_events), n_censored={len(events) - events.sum()}")
        print(f"  - survtimes shape: {survtimes.shape}, dtype: {survtimes.dtype}")
        print(f"  - survtimes stats: min={survtimes.min():.2f}, max={survtimes.max():.2f}, "
              f"mean={survtimes.mean():.2f}, median={np.median(survtimes):.2f}\n")
    else:
        y_test = np.concatenate(y_test, axis=0)
    
    c_test = np.concatenate(c_test, axis=0)
    
    # Run prediction
    trainer_pred = pl.Trainer(
        accelerator=config.hardware.accelerator,
        devices=config.hardware.devices,
        logger=False,
    )

    batch_results = trainer_pred.predict(model, val_dloader)
    
    if config.concepts.no_concepts:
        # No concepts mode: handle missing concept outputs
        c_probs = None
        c_embs = None
        ctxts = None
        concept_attention_weights = None
        y_probs = get_yprobs(batch_results, task_type=config.task_type)
    else:
        # Original concept-based mode
        c_probs = get_cptprobs(batch_results, True if config.concepts.concept_states else False)
        y_probs = get_yprobs(batch_results, task_type=config.task_type)
        c_embs = get_cembs(batch_results)
        concept_attention_weights = get_concept_attention_weights(batch_results)
        
        # Reshape concept embeddings
        if c_embs is not None:
            expected_emb_dim_per_sample = config.concepts.n_concepts * config.model.emb_dim
            if c_embs.size == c_test.shape[0] * expected_emb_dim_per_sample:
                c_embs = np.reshape(c_embs, (c_test.shape[0], config.concepts.n_concepts, config.model.emb_dim))
        
        ctxts = get_contexts(batch_results)
    
    patient_ids = patient_ids_list
    return [c_probs, c_test, y_probs, y_test, c_embs, ctxts, concept_attention_weights, patient_ids]


def train(
    train_cohort: pd.DataFrame,
    concepts: List[str],
    db_path: str,
    config,
    experiment_name: Optional[str] = None,
    version: Optional[str] = None,
    train_data: Optional[pd.DataFrame] = None,
    val_data: Optional[pd.DataFrame] = None,
    run_id: Optional[Any] = None,
    run_metadata: Optional[dict] = None,
) -> Tuple[List, pl.Trainer, Optional[pd.DataFrame]]:
    """Train model with optional pre-split data.
    
    If train_data and val_data are provided, uses them directly.
    Otherwise, splits train_cohort into train/val sets.
    
    Args:
        train_cohort: Full training dataset DataFrame (used if train_data/val_data not provided)
        concepts: List of concept column names
        db_path: Path to database directory
        config: Configuration object
        experiment_name: Optional experiment name for TensorBoard
        version: Optional version string for TensorBoard
        train_data: Optional pre-split training data DataFrame
        val_data: Optional pre-split validation data DataFrame
        run_id: Optional identifier for this run (e.g. (repeat, fold)); written to CSV when saving.
        run_metadata: Optional dict of extra columns (e.g. fold, repeat, combination) for the predictions DataFrame.
        
    Returns:
        Tuple of (results, trainer, predictions_df). predictions_df is None if config.output.save_path is not set.
    """
    # Split data if not provided
    if train_data is None or val_data is None:
        train_data, val_data = split_train_val(train_cohort, concepts, config)
    
    # Setup concept weights based on training data
    if not config.concepts.no_concepts:
        cpt_cls_weights = get_concept_weights(train_data, concepts)
        config.concepts.cpt_cls_weights = cpt_cls_weights
    else:
        config.concepts.cpt_cls_weights = None
    
    # Get data loaders
    train_dloader, val_dloader = get_data_loaders(
        db_path,
        train_data=train_data,
        val_data=val_data,
        config=config
    )

    # Train model
    model, trainer = train_model(
        train_dloader, 
        val_dloader, 
        config, 
        experiment_name=experiment_name, 
        version=version
    )
    
    # Run prediction
    results = predict(model, val_dloader, config)
    
    # Compute and print validation metrics
    c_probs, c_test, y_probs, y_test, c_embs, ctxts, concept_attention_weights, patient_ids = results
    
    # Compute concept metrics using unified functions from metrics.py
    # NOTE:
    # - c_probs currently contains raw logits from the model (see ConceptEmbeddingModel._forward
    #   and get_cptprobs in training.utils).
    # - compute_concept_metrics can internally handle logits when is_logits=True
    #   (it applies sigmoid/softmax where appropriate before thresholding).
    # If this flag is left as False, the logits are treated as probabilities directly,
    # which shifts the effective classification threshold and can severely degrade F1.
    if not config.concepts.no_concepts and c_probs is not None:
        concept_metrics = compute_concept_metrics(
            c_probs, c_test, config.concepts.concept_states, is_logits=True
        )
        
        # Extract F1 scores for binary/categorical concepts
        f1_values = [m['f1'] for m in concept_metrics.values() if 'f1' in m]
        if f1_values:
            print(f"  concept_f1: {np.mean(f1_values)*100:.2f}%")
        
        # Extract MSE for continuous concepts
        mse_values = [m['mse'] for m in concept_metrics.values() if 'mse' in m]
        if mse_values:
            print(f"  concept_mse: {np.mean(mse_values):.4f}")
    
    # Compute task metrics
    task_metrics = compute_task_metrics_all(y_probs, y_test, config.task_type)
    
    if task_metrics is not None:
        if config.task_type == 'cox':
            print(f"  c_index: {task_metrics['c_index']*100:.2f}%")
        elif config.task_type == 'continuous':
            print(f"  mse: {task_metrics.get('mse', 0.0):.4f}")
        else:
            print(f"  roc_auc: {task_metrics['roc_auc']*100:.2f}%")
            print(f"  f1: {task_metrics['f1']*100:.2f}%")

    predictions_df = None
    if config.output.save_path:
        predictions_df = build_predictions_dataframe(
            patient_ids,
            [c_probs, c_test, y_probs, y_test],
            config,
            run_id=run_id,
            run_metadata=run_metadata,
            c_embs=c_embs,
        )

    return results, trainer, predictions_df


